pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/faelsou/gerador-senha.git'
            }
        }
        agent {
            docker {
                image 'jenkins-root:1.2' // Substitua pela sua imagem Docker
                args '-u root:root' // Executa o contêiner como root       docker push meu_usuario/meu_aplicativo:1.0 
        stage('Setup') {
            steps {
                // Adicione os passos de setup aqui (ex: instalar dependências)
                sh 'sudo mkdir -p /var/lib/apt/lists/partial && sudo chown -R jenkins:jenkins /var/lib/apt/lists'
                //sh 'rm -rf /var/lib/apt/lists/* && apt clean && fsck -f /'
                sh 'apt update && apt install python3-pip -y'
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Deploy') {
            steps {
                // Adicione os passos de deploy aqui (ex: copiar arquivos para o servidor)
                sh 'python3 app.py'
                echo 'Deploying application...'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}