pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/faelsou/gerador-senha.git'
            }
        }
        
        stage('Setup') {
            steps {
                // Adicione os passos de setup aqui (ex: instalar dependências)
                sh 'sudo apt update && sudo apt install python3 -y'
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Deploy') {
            steps {
                // Adicione os passos de deploy aqui (ex: copiar arquivos para o servidor)
                sh 'python3 app.py'
                echo 'Deploying application...'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}